# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[package]
name = "katalon"
version = "0.1.0"
edition = "2018"

[dependencies]
regex = "1.5"
rand = "0.8"
primal = "0.2"
tabled = "0.7"
